# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - master
pr:
  branches:
    exclude:
      - "master"

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cab670d4-ea8b-47cf-8844-fdf6949a8511'
  imageRepository: 'simflightstracker'
  containerRegistry: 'nodeninja-f8c9bdgffpf6b5ga.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-24.04'

stages:
- stage: Build
  displayName: Compile Build and Push
  jobs:
  - job: BuildImage
    displayName: "Build Docker Image"
    pool:
      vmImage: $(vmImageName)
    steps:
    # Extract the version from pom.xml and set it as a pipeline variable
    - script: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "App version is: $VERSION"
        echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$VERSION"
        echo "##vso[task.setvariable variable=LOCAL_APP_VERSION]$VERSION"
      displayName: 'Extract version from pom.xml'
      name: SetVersion

    - task: Maven@4
      displayName: Maven compile java app
      inputs:
        azureSubscription: 'Main Subscription(98a0acc1-cf43-4cf6-8485-208999a388a6)'
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(LOCAL_APP_VERSION)
- stage: Deploy
  dependsOn: Build
  displayName: Deployment
  variables:
    APP_VERSION: $[stageDependencies.Build.BuildImage.outputs['SetVersion.APP_VERSION']]
  jobs:
   - deployment: DeployToProd
     displayName: "Deploy Container to App Service"
     environment: production
     strategy:
      runOnce:
        deploy:
          steps:
            - checkout: none
            - task: AzureWebAppContainer@1
              inputs:
                azureSubscription: 'Main Subscription(98a0acc1-cf43-4cf6-8485-208999a388a6)'
                appName: 'sim-flights-tracker'
                containers: '$(containerRegistry)/$(imageRepository):$(APP_VERSION)'

