spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}/${MONGO_DB}

sft:
  ivao:
    oauth:
      client-id: ${IVAO_CID}
      client-secret: ${IVAO_CST}
      grant-type: client_credentials
      scope: openid
      token-uri: https://api.ivao.aero/v2/oauth/token
    host: https://api.ivao.aero


  vatsim:
    oauth:
      client-id: ${VATSIM_CID}
      client-secret: ${VATSIM_CST}
      grant-type: authorization_code
      scope: openid
      token-uri: ${VATSIM_AUTH_SERVER}/oauth/token
      redirect-uri: ${AUTH_REDIRECT_URL}
      user-details: ${VATSIM_AUTH_SERVER}/api/user
    host:
      v2: https://my.vatsim.net/api/v2
      v3: https://data.vatsim.net/v3
      metar: https://metar.vatsim.net
      core: https://api.vatsim.net/v2

  firebase:
    project-name: ${FIREBASE_PROJECT_NAME}
    project-number: ${FIREBASE_PROJECT_NAME}
    app-check-jwk: https://firebaseappcheck.googleapis.com/v1/jwks

  timings:
    vatsim-data-delay: "PT20S"
    ivao-data-delay: "PT20S"
  app-check-off: ${APP_CHECK_OFF}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: INFO
    org.springframework: INFO