spring:
  data:
    mongodb:
      database: simflightstracker
      uri: mongodb+srv://apps:${MONGO_PASS}@sft.lmbdj.mongodb.net
  codec:
    max-in-memory-size: 4MB

sft:
  ivao:
    oauth:
      client-id: ${IVAO_CID}
      client-secret: ${IVAO_CST}
      grant-type: client_credentials
      scope: openid
      token-uri: https://api.ivao.aero/v2/oauth/token
    host:
      v2: https://api.ivao.aero/v2


  vatsim:
    host:
      v2: https://my.vatsim.net/api/v2
      v3: https://data.vatsim.net/v3
      metar: https://metar.vatsim.net