spring:
  data:
    mongodb:
      database: simflightstracker
      uri: mongodb+srv://apps:${MONGO_PASS}@sft.lmbdj.mongodb.net

sft:
  ivao:
    oauth:
      client-id: ${IVAO_CID}
      client-secret: ${IVAO_CST}
      grant-type: client_credentials
      scope: openid
      token-uri: https://api.ivao.aero/v2/oauth/token
    host: https://api.ivao.aero


  vatsim:
    oauth:
      client-id: ${VATSIM_CID}
      client-secret: ${VATSIM_CST}
      grant-type: client_credentials
      scope: openid
      token-uri: https://data.vatsim.net/v2/oauth/token
    host:
      v2: https://my.vatsim.net/api/v2
      v3: https://data.vatsim.net/v3
      metar: https://metar.vatsim.net
      core: https://api.vatsim.net/v2

  firebase:
    project-name: ${FIREBASE_PROJECT_NAME}
    project-number: ${FIREBASE_PROJECT_NAME}
    app-check-jwk: https://firebaseappcheck.googleapis.com/v1/jwks

  timings:
    vatsim-data-delay: "PT20S"
    ivao-data-delay: "PT20S"
  app-check-off: false

logging:
  level:
    root: INFO
    org.springframework: INFO